dataset: dataset_name_GAIA
path:
    case_dir: data/GAIA/cases.csv
    graph_dir: data/GAIA/graphs_info/ # just for node_hash to map the pod to id
    sample_dir: data/GAIA/test_samples/

feat_dim:
    metric: 183
    trace: 10
    log: 768
 
train_samples_num: whole # Number of training samples. Choose 'whole' if all samples are selected.

model_param:
    num_layers: 3 # The number of layers of the encoder/decoder.
    in_dim: 961
    # in_dim: 213
    hidden_dim: 710
    out_dim: 32
    noise_rate: 0.5
    epochs: 1000
    batch_size: 128
    learning_rate: 0.001
    norm: none
    aug_multiple: 5
    feat_span: # Dimension initiation for different types of features. Only required when selecting ModalLoss function.
        -
            - 0
            - 182
        - 
            - 183
            - 192
        -
            - 193
            - 960

feedback:
    frozen: True
    epochs: 50
    batch_size: 4
    window_size: 10
    learning_rate: 0.01
    sample_num: 0.3 # The integer type indicates the number of samples for feedback, and the float type indicates the sample proportion.
    mask_rate: 0 # The probability of randomly masking node features when feedback.